<a href="https://colab.research.google.com/github/AunAli6783/python-/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)


2.6.0+cu124


In [ ]:
scalar =torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape


torch.Size([])

In [ ]:
vector=torch.tensor([1,2])
vector

tensor([1, 2])

In [ ]:
print(vector.ndim)
print(vector.shape)

1
torch.Size([2])


In [ ]:
vector=torch.tensor([[[[1,2],
          [4,5],
          [4,5]]]])

In [ ]:
print(vector.ndim)
print(vector.shape)

4
torch.Size([1, 1, 3, 2])


In [ ]:
random = torch.rand(1,10)
random

tensor([[0.7743, 0.4883, 0.4506, 0.4014, 0.6159, 0.6778, 0.2920, 0.5338, 0.1865,
         0.2204]])

In [ ]:
random2=torch.rand(3,4,4)
random2

tensor([[[4.3932e-01, 7.9057e-01, 9.3029e-01, 7.3378e-02],
         [7.2313e-01, 6.4598e-01, 1.3442e-01, 2.9078e-01],
         [8.7680e-01, 2.6166e-05, 4.7343e-01, 4.0963e-01],
         [3.1538e-01, 4.5693e-01, 2.4625e-01, 8.0219e-01]],

        [[1.9521e-01, 7.1431e-01, 4.5782e-01, 4.6632e-01],
         [5.5459e-01, 6.2056e-01, 7.4262e-01, 1.7673e-01],
         [5.1730e-01, 2.5695e-01, 5.9917e-01, 3.3514e-02],
         [1.5484e-01, 6.0505e-01, 4.1745e-01, 1.1808e-01]],

        [[6.6660e-01, 7.6329e-01, 1.8544e-01, 5.4468e-01],
         [1.2438e-01, 4.3545e-01, 5.4925e-01, 5.4119e-01],
         [7.2699e-02, 7.3549e-01, 3.8483e-01, 9.1639e-01],
         [8.4985e-01, 1.9803e-01, 7.4226e-01, 3.2133e-01]]])

In [ ]:
random2.shape , random2.ndim , random2.dtype

(torch.Size([3, 4, 4]), 3, torch.float32)

In [ ]:
random3=torch.zeros(1,2,3)
random3

tensor([[[0., 0., 0.],
         [0., 0., 0.]]])

In [ ]:
random4=torch.ones(2,2,2,2)
random4

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [ ]:
random5=torch.arange(0,10,4)
random5

tensor([0, 4, 8])

In [ ]:
random6=torch.arange(100,1000,100, dtype=torch.int)
random6

tensor([100, 200, 300, 400, 500, 600, 700, 800, 900], dtype=torch.int32)

In [ ]:
random7=torch.zeros_like(random6)
random7

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32)

In [ ]:
dt=torch.rand(3,10 ,dtype=torch.float32 , device='cuda')
dt

tensor([[0.1096, 0.6108, 0.0075, 0.2196, 0.1438, 0.7944, 0.4227, 0.9319, 0.0148,
         0.2404],
        [0.2462, 0.5875, 0.2916, 0.5260, 0.4565, 0.0396, 0.3538, 0.4487, 0.8752,
         0.4508],
        [0.5026, 0.8946, 0.0091, 0.0366, 0.1270, 0.3985, 0.7137, 0.2601, 0.1653,
         0.0682]], device='cuda:0')

In [ ]:
t1=torch.rand(2,10)
t1

tensor([[0.5760, 0.0175, 0.6075, 0.9306, 0.9783, 0.8667, 0.4563, 0.4950, 0.6928,
         0.0204],
        [0.7012, 0.0635, 0.7805, 0.0723, 0.5204, 0.1972, 0.5984, 0.5571, 0.7427,
         0.9504]])

In [ ]:
t1=t1+10
t1



tensor([[10.5760, 10.0175, 10.6075, 10.9306, 10.9783, 10.8667, 10.4563, 10.4950,
         10.6928, 10.0204],
        [10.7012, 10.0635, 10.7805, 10.0723, 10.5204, 10.1972, 10.5984, 10.5571,
         10.7427, 10.9504]])

In [ ]:
t1=t1*2
t1

tensor([[21.1521, 20.0350, 21.2151, 21.8613, 21.9566, 21.7333, 20.9127, 20.9900,
         21.3857, 20.0408],
        [21.4024, 20.1270, 21.5611, 20.1447, 21.0407, 20.3945, 21.1967, 21.1142,
         21.4855, 21.9007]])

In [ ]:
t1=t1 % 2
t1

tensor([[1.1521, 0.0350, 1.2151, 1.8613, 1.9566, 1.7333, 0.9127, 0.9900, 1.3857,
         0.0408],
        [1.4024, 0.1270, 1.5611, 0.1447, 1.0407, 0.3945, 1.1967, 1.1142, 1.4855,
         1.9007]])

In [ ]:
t1.shape

torch.Size([2, 10])

In [ ]:
t2=torch.rand(10,2)
t2

tensor([[0.8892, 0.1161],
        [0.2004, 0.6472],
        [0.2549, 0.2814],
        [0.9973, 0.0297],
        [0.5613, 0.0242],
        [0.9119, 0.1028],
        [0.8440, 0.4781],
        [0.2166, 0.6873],
        [0.8548, 0.7524],
        [0.7410, 0.1048]])

In [ ]:
t3=torch.matmul(t1,t2)
t3

tensor([[8.0757, 2.9430],
        [6.6882, 3.4092]])

In [ ]:
t3=t3.T


tensor([[8.0757, 6.6882],
        [2.9430, 3.4092]])

In [ ]:
t3


tensor([[8.0757, 2.9430],
        [6.6882, 3.4092]])

In [ ]:
print(f'min :{t3.min()}')
print(f'max :{t3.max()}')
print(f'mean :{t3.mean()}')
print(f'sum :{t3.sum()}')

min :2.942953109741211
max :8.075705528259277
mean :5.279005527496338
sum :21.11602210998535


In [ ]:
min=t3.argmin()
max=t3.argmax()
print(min,max)

tensor(1) tensor(0)


In [ ]:
t3

tensor([[8.0757, 2.9430],
        [6.6882, 3.4092]])

In [ ]:
t4=torch.rand(3,10)
t4


tensor([[0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073, 0.0827, 0.1697, 0.6541,
         0.4596],
        [0.5129, 0.3394, 0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439, 0.5630,
         0.4698],
        [0.8154, 0.0327, 0.0277, 0.2942, 0.7889, 0.4184, 0.5768, 0.5137, 0.0439,
         0.9968]])

In [ ]:
t4.reshape(5,6)

tensor([[0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
        [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
        [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
        [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
        [0.7889, 0.4184, 0.5768, 0.5137, 0.0439, 0.9968]])

In [ ]:
t4

tensor([[0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073, 0.0827, 0.1697, 0.6541,
         0.4596],
        [0.5129, 0.3394, 0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439, 0.5630,
         0.4698],
        [0.8154, 0.0327, 0.0277, 0.2942, 0.7889, 0.4184, 0.5768, 0.5137, 0.0439,
         0.9968]])

In [ ]:
t5=t4.view(5,6)

In [ ]:
t5.shape

torch.Size([5, 6])

In [ ]:
t6=torch.stack([t5,t5,t5,t5],dim=1)
t6

tensor([[[0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
         [0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
         [0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
         [0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073]],

        [[0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
         [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
         [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
         [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394]],

        [[0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
         [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
         [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
         [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439]],

        [[0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
         [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
         [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
         [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942]],

        [[0.7889, 0.4184, 0.5768, 0.5137, 0.0439

In [ ]:
t6

tensor([[[0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
         [0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
         [0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073],
         [0.1510, 0.7725, 0.8991, 0.9820, 0.8198, 0.2073]],

        [[0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
         [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
         [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394],
         [0.0827, 0.1697, 0.6541, 0.4596, 0.5129, 0.3394]],

        [[0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
         [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
         [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439],
         [0.3839, 0.0458, 0.0458, 0.6803, 0.4296, 0.3439]],

        [[0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
         [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
         [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942],
         [0.5630, 0.4698, 0.8154, 0.0327, 0.0277, 0.2942]],

        [[0.7889, 0.4184, 0.5768, 0.5137, 0.0439

In [ ]:
t7=torch.rand(9,2,1)
t7

tensor([[[0.2017],
         [0.8081]],

        [[0.4107],
         [0.5800]],

        [[0.0159],
         [0.2815]],

        [[0.5165],
         [0.0816]],

        [[0.8720],
         [0.2708]],

        [[0.6225],
         [0.3308]],

        [[0.6015],
         [0.6246]],

        [[0.7370],
         [0.4526]],

        [[0.7284],
         [0.1322]]])

In [ ]:
t7.squeeze()

tensor([[0.2017, 0.8081],
        [0.4107, 0.5800],
        [0.0159, 0.2815],
        [0.5165, 0.0816],
        [0.8720, 0.2708],
        [0.6225, 0.3308],
        [0.6015, 0.6246],
        [0.7370, 0.4526],
        [0.7284, 0.1322]])

In [ ]:
t7.unsqueeze(dim=1)

tensor([[[[0.2017],
          [0.8081]]],


        [[[0.4107],
          [0.5800]]],


        [[[0.0159],
          [0.2815]]],


        [[[0.5165],
          [0.0816]]],


        [[[0.8720],
          [0.2708]]],


        [[[0.6225],
          [0.3308]]],


        [[[0.6015],
          [0.6246]]],


        [[[0.7370],
          [0.4526]]],


        [[[0.7284],
          [0.1322]]]])

In [ ]:
t8=torch.rand(size=(224,224,3))
t8

tensor([[[0.9995, 0.6960, 0.4251],
         [0.2418, 0.9863, 0.7567],
         [0.2878, 0.4685, 0.5414],
         ...,
         [0.0401, 0.7056, 0.3549],
         [0.0372, 0.6114, 0.6975],
         [0.5308, 0.3544, 0.6144]],

        [[0.2151, 0.1950, 0.8934],
         [0.6009, 0.2712, 0.3351],
         [0.9671, 0.6700, 0.7671],
         ...,
         [0.4338, 0.2992, 0.6848],
         [0.2083, 0.7422, 0.8624],
         [0.5812, 0.3335, 0.2663]],

        [[0.2022, 0.3408, 0.1576],
         [0.2973, 0.1362, 0.2985],
         [0.9547, 0.8882, 0.5319],
         ...,
         [0.5050, 0.5396, 0.1869],
         [0.6748, 0.1277, 0.2948],
         [0.8725, 0.4429, 0.6492]],

        ...,

        [[0.1516, 0.6957, 0.7872],
         [0.1902, 0.8054, 0.8063],
         [0.1538, 0.6240, 0.0967],
         ...,
         [0.5984, 0.7464, 0.9012],
         [0.9657, 0.7885, 0.0344],
         [0.2644, 0.6931, 0.1481]],

        [[0.1409, 0.9378, 0.8711],
         [0.5754, 0.8293, 0.8527],
         [0.

In [ ]:
t8.permute(2,0,1)
t8.shape

torch.Size([224, 224, 3])

In [ ]:
## some changes for git

In [2]:
import torch


In [3]:
torch.cuda.is_available()


True

In [4]:
torch.cuda.device_count()

1

In [5]:
!nvidia-smi

Sat Jun 28 12:31:07 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   52C    P8              9W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [6]:
device ='cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [9]:
t1=torch.tensor([1,2,3,4])
t1

tensor([1, 2, 3, 4])

In [12]:
t2=t1.to(device)

In [14]:
t2.cpu().numpy()

array([1, 2, 3, 4])